version: 2
updates:
  # Backend dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'backend'
    commit-message:
      prefix: 'chore(backend)'
      include: 'scope'

  # Frontend dependencies
  - package-ecosystem: 'npm'
    directory: '/ui'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'frontend'
    commit-message:
      prefix: 'chore(frontend)'
      include: 'scope'
